security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PARTICULAR:    ROLE_USER
        ROLE_PROFESSIONAL:      ROLE_PARTICULAR
        ROLE_ADMIN:       ROLE_PROFESSIONAL
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    providers:
        fos_userbundle:
#            id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email #login by username or email
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                success_handler: authentication_handler
                default_target_path: vente_index
                always_use_default_target_path: true
            logout:       true

            anonymous:    true

            entry_point: fbn_user.login_entry_point

        login:
            pattern:  ^/login$
            security: false


    access_control:
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/market/new, role: ROLE_PROFESSIONAL }
